define([
	"jquery",
	"jquery.bootstrap",
	"bootstrap-switch",
	"jquery.ui",
	"underscore",
	"backbone",
	"backbone.marionette",
	"backbone.localStorage",
	"backbone.validation",
	"backbone.zingchart",
	"backbone.auth",
	"moment",
	"text",
], function() { });